# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  baseImageName: 'resinbuilder-base:$(build.buildId)'
  imageName: 'balena-builder:$(build.buildId)'

steps:
- script: |
    cd base 
    docker build -f Dockerfile -t $(dockerId)/$(baseImageName) .
    cd ../builder
    docker build -f Dockerfile -t $(dockerId)/$(imageName) .
  displayName: 'docker build'
